# Mastodon to Memos Localization Messages.
# Copyright (C) 2025 Pierre QUILLERY
# This file is distributed under the same license as the Mastodon2Memos package.
# Pierre <pierre@quillery.fr>, 2025.
#
msgid ""
msgstr ""
"Project-Id-Version: Mastodon2Memos 1.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-01-15 21:55+0100\n"
"PO-Revision-Date: 2025-01-15 21:44+0100\n"
"Last-Translator: Pierre Quillery <pierre@quillery.fr>\n"
"Language-Team: Italian <tp@lists.linux.it>\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: mastodon2memos/commands/__init__.py:16
#: mastodon2memos/commands/commands.py:16
#, python-brace-format
msgid ""
"Configuration file not found at {config_path}. Please ensure the file exists."
msgstr ""
"File di configurazione non trovato in {config_path}. Assicurati che il file "
"esista."

#: mastodon2memos/commands/__init__.py:29
#: mastodon2memos/commands/commands.py:29
#, python-brace-format
msgid "Missing section \"{section}\" in configuration file."
msgstr "Sezione \"{section}\" mancante nel file di configurazione."

#: mastodon2memos/commands/__init__.py:33
#: mastodon2memos/commands/commands.py:33
#, python-brace-format
msgid "Missing key \"{key}\" in section \"{section}\" of configuration file."
msgstr ""
"Chiave \"{key}\" mancante nella sezione \"{section}\" del file di "
"configurazione."

#: mastodon2memos/commands/__init__.py:60
#: mastodon2memos/commands/commands.py:60
msgid "Successfully connected to Mastodon API."
msgstr "Connessione alla API di Mastodon riuscita."

#: mastodon2memos/commands/__init__.py:62
#: mastodon2memos/commands/commands.py:62
msgid "Failed to connect to Mastodon API."
msgstr "Connessione alla API di Mastodon fallita."

#: mastodon2memos/commands/__init__.py:69
#: mastodon2memos/commands/commands.py:69
msgid "Successfully connected to Memos API."
msgstr "Connessione alla API di Memos riuscita."

#: mastodon2memos/commands/__init__.py:71
#: mastodon2memos/commands/commands.py:71
msgid "Failed to connect to Memos API."
msgstr "Connessione alla API di Memos fallita."

#: mastodon2memos/commands/mastodon2memos.py:6
msgid "Publish Mastodon toots as Memos."
msgstr "Pubblica i toot di Mastodon come Memos."

#: mastodon2memos/commands/mastodon2memos.py:7
msgid "Ask before creating a new memo from a toot."
msgstr "Chiedi prima di creare un nuovo memo da un toot."

#: mastodon2memos/commands/mastodon2memos.py:8
#: mastodon2memos/commands/troubleshoot.py:7
msgid "Path to the configuration file."
msgstr "Percorso al file di configurazione."

#: mastodon2memos/commands/mastodon2memos.py:25
#, python-brace-format
msgid "Processing toot: {url}"
msgstr "Elaborazione toot: {url}"

#: mastodon2memos/commands/mastodon2memos.py:28
#, python-brace-format
msgid ""
"Do you want to attempt publishing this toot as a memo?\n"
"{content}\n"
"{url}?"
msgstr ""
"Vuoi tentare di pubblicare questo toot come un memo?\n"
"{content}\n"
"{url}?"

#: mastodon2memos/commands/mastodon2memos.py:29
msgid "Skipping toot."
msgstr "Toot saltato."

#: mastodon2memos/commands/mastodon2memos.py:33
msgid "New toot added to memos."
msgstr "Nuovo toot aggiunto ai memos."

#: mastodon2memos/commands/mastodon2memos.py:35
msgid "No memo added, toot was already saved in memos."
msgstr "Nessun memo aggiunto, toot gi√† salvato nei memos."

#: mastodon2memos/commands/mastodon2memos.py:37
msgid "Finished processing toots."
msgstr "Elaborazione dei toot completata."

#: mastodon2memos/commands/troubleshoot.py:6
msgid "Ensure proper connection to both Mastodon and Memos APIs."
msgstr ""
"Assicurati di avere una connessione adeguata con entrambe le API di Mastodon "
"e Memos."

#: mastodon2memos/commands/troubleshoot.py:20
#, python-brace-format
msgid "Successfully resolved Mastodon username to user ID: {user_id}"
msgstr "Nome utente di Mastodon risolto con successo in ID utente: {user_id}"

#: mastodon2memos/commands/troubleshoot.py:22
msgid "Failed to resolve Mastodon username to user ID."
msgstr "Impossibile risolvere il nome utente di Mastodon in ID utente."

#: mastodon2memos/clients/mastodon.py:51
#, python-brace-format
msgid "Failed to fetch latest public toots: {error}"
msgstr "Impossibile recuperare gli ultimi toot pubblici: {error}"

#: mastodon2memos/clients/memos.py:42
#, fuzzy, python-brace-format
msgid "> üåê [original toot]({url}) posted by [{acct}]({account_url}) #{tag}"
msgstr ""
"> üåê [toot originale]({url}) pubblicato da [{acct}]({account_url}) #{tag}"
